apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  ports:
    - protocol: TCP
      name: otel
      port: 8888
      targetPort: 8888
        #- protocol: TCP
        #name: kubeletstat
        # port: 10250
        #targetPort: 10250
  selector:
    app.kubernetes.io/instance: otel-collector
